### ISSUE TITLE
potential bug in formatChartData - variable double incremented

### ISSUE THREAD

**Issue by jordanreedie** [rifflearning/mattermost-webapp#43]
https://github.com/rifflearning/mattermost-webapp/blob/9cd7982c90ca4def4900b3414a312bb1d4bebc8f/components/dashboard/components/TurnChart.js#L20-L46

Two questions about this function:

1. It looks like colorOther is never used. Is that just an artifact from a refactor?

2. In lines 40 & 41, in the case we do not have a display name from firebase, nextOtherUser will be incremented twice. I imagine that is unintentional? Is it even possible for a user to not have a display name in this view?

**Comment by mlippert** [comment]
indeed `colorOther` is never used, along w/ a bunch of other stuff (check-style pointed out many similar things I'm cleaning up now)
- there is definitely a double increment of nextOtherUser
- there are only 4 peer colors but I think we're supporting 7 total participants which means we'd
  need 6 peer colors, and we really should gracefully handle more (perhaps by cycling around?

**Comment by adonahue** [comment]
@mlippert - it sounds like maybe you fixed this? Can this be close?

**Comment by mlippert** [comment]
This was fixed in commit 4417758444779dc3b1900e2ae416329987438896
