### ISSUE TITLE
Riff Metrics: Turn Chart only uses participant's last utterance in the meeting

### ISSUE THREAD

**Issue by mlippert** [rifflearning/mattermost-webapp#86]
## Description

The Turn Chart metric isn't correctly accumulating the total time a participant spent
talking in the meeting, it is only using the participant's last utterance.

### Steps to Reproduce
Have a meeting preferably w/ several people having some discussion amonst the
participants, such that everyone speaks at least twice.
End the meeting and view the Riff Metrics on the Dashboard page.
It's a little hard to know how long each participant actually spent talking, but you
should see that the time list is way too short for each participant.

### Expected behavior
The time allocated to each participant should be the total time of all of their utterances
not just the last one.

### Possible Solution
The cause is actually known. There is a bug in the utility function `groupByPropertyValue`
such that instead of adding element's to the value's array, replaces the array w/ a new
array with the last element. This has already been fixed in the `riff-rtc` repository in commit rifflearning/riff-rtc@f308119289f3dfe514ad3378d35ecda71544c881.

### Site the bug occurred on:
localhost (development machine)

### Additional Context
The bug was manifested by the cleanup of the dashboard in commit d6394028b351ffeb28a25db1b4aa71e4376051c4 which used the `groupByPropertyValue` function for processing utterances. This commit is in version `1.0.0-dev.27`

**Comment by ebporter** [comment]
This still needs to be tested in Mattermost.

**Comment by adonahue** [comment]
Verified on staging.
