### ISSUE TITLE
Integrate new code from Brightscout into Riff EDU

### ISSUE THREAD

**Issue by ebporter** [rifflearning/mattermost-webapp#91]
This task is for integrating new code from Brightscout to support surveys into Riff EDU. This is an ongoing task as Brightscout continues to release new code.

**Comment by adonahue** [comment]
@mlippert - can I close this story or do you want to use it to track taking ownership of the Repo?

**Comment by mlippert** [comment]
I'd say even though this was just for work in the previous iteration, we might as well hang on to this story until we've taken ownership of the repo. Silly to create another story

**Comment by adonahue** [comment]
ok cool, just stick in play when you start the work.

**Comment by mlippert** [comment]
The repo is transferred https://github.com/rifflearning/mattermost-plugin-survey

However, I'm having some issues adding it to zenhub that I have to figure out or contact support about.

**Comment by mlippert** [comment]
OK, that worked itself out and the repository has been added to this workspace successfully.

**Comment by mlippert** [comment]
Actually before this gets closed out perhaps @jaedoucette wants to review the documentation they wrote?
1. [Overview](https://github.com/rifflearning/mattermost-plugin-survey/blob/master/docs/overview.md)
1. [Survey Schema Design](https://github.com/rifflearning/mattermost-plugin-survey/blob/master/docs/db_schema.md)

**Comment by jaedoucette** [comment]
Thanks Mike. I've submitted a PR to address the one ambiguity I saw.
Otherwise, looks good.
---------------------------
John Doucette, PhD
Principal Scientist, Riff Learning
john@rifflearning.com
760-642-9199
